state_crop_dict = {'Gujarat': ['Sugarcane',
  'Cotton(lint)',
  'Onion',
  'Groundnut',
  'Potato',
  'Wheat',
  'Oilseeds total',
  'Banana',
  'Maize',
  'Bajra'],
 'Goa': ['Coconut ',
  'Rice',
  'Sugarcane',
  'Other Vegetables',
  'Other Fresh Fruits',
  'Cashewnut',
  'Banana',
  'Other  Rabi pulses',
  'Groundnut',
  'Mango'],
 'Nagaland': ['Sugarcane',
  'Rice',
  'Niger seed',
  'Potato',
  'Jute',
  'Maize',
  'Rapeseed &Mustard',
  'Tapioca',
  'Soyabean',
  'Oilseeds total'],
 'Tripura': ['Rice',
  'Potato',
  'Sugarcane',
  'Jute & mesta',
  'Mesta',
  'Jute',
  'Oilseeds total',
  'Maize',
  'Other Kharif pulses',
  'other oilseeds'],
 'Jammu and Kashmir ': ['Wheat',
  'Maize',
  'Rice',
  'Rapeseed &Mustard',
  'Bajra',
  'Potato',
  'Other Vegetables',
  'Jowar',
  'Barley',
  'Urad'],
 'Karnataka': ['Sugarcane',
  'Coconut ',
  'Dry ginger',
  'Maize',
  'Paddy',
  'Arecanut',
  'Arhar/Tur',
  'Cotton(lint)',
  'Banana',
  'Rice'],
 'Jharkhand': ['Rice',
  'Potato',
  'Wheat',
  'Maize',
  'Ragi',
  'Sugarcane',
  'Arhar/Tur',
  'Onion',
  'Masoor',
  'Gram'],
 'Himachal Pradesh': ['Wheat',
  'Maize',
  'Rice',
  'Potato',
  'Sugarcane',
  'Dry ginger',
  'Peas & beans (Pulses)',
  'Ginger',
  'Barley',
  'Small millets'],
 'Rajasthan': ['Wheat',
  'Bajra',
  'Rapeseed &Mustard',
  'Maize',
  'Guar seed',
  'Sugarcane',
  'Cotton(lint)',
  'Soyabean',
  'Gram',
  'Barley'],
 'Uttarakhand': ['Sugarcane',
  'Total foodgrain',
  'Wheat',
  'Rice',
  'Onion',
  'Potato',
  'Ragi',
  'Other Cereals & Millets',
  'Small millets',
  'Maize'],
 'Dadra and Nagar Haveli': ['Sugarcane',
  'Coconut ',
  'Rice',
  'Other  Rabi pulses',
  'Ragi',
  'Other Kharif pulses',
  'Arhar/Tur',
  'Urad',
  'Wheat',
  'Banana'],
 'Odisha': ['Rice',
  'Paddy',
  'Sugarcane',
  'Maize',
  'Sweet potato',
  'Onion',
  'Groundnut',
  'Jute',
  'Moong(Green Gram)',
  'Ragi'],
 'Manipur': ['Rice',
  'Banana',
  'Pineapple',
  'Potato',
  'Sugarcane',
  'Maize',
  'Other Fresh Fruits',
  'Dry ginger',
  'Cabbage',
  'Dry chillies'],
 'Chandigarh': ['Wheat',
  'Potato',
  'Maize',
  'Rice',
  'Onion',
  'Rapeseed &Mustard',
  'Arhar/Tur',
  'Masoor',
  'Urad',
  'Sunflower'],
 'Mizoram': ['Rice',
  'Sugarcane',
  'Maize',
  'Tapioca',
  'Other Kharif pulses',
  'other oilseeds',
  'Other  Rabi pulses',
  'Potato',
  'Sesamum',
  'Rapeseed &Mustard'],
 'Assam': ['Coconut ',
  'Sugarcane',
  'Rice',
  'Paddy',
  'Jute',
  'Potato',
  'Banana',
  'Pineapple',
  'Orange',
  'Ginger'],
 'Tamil Nadu': ['Coconut ',
  'Sugarcane',
  'Tapioca',
  'Banana',
  'Rice',
  'Total foodgrain',
  'Guar seed',
  'Maize',
  'Mango',
  'Groundnut'],
 'Kerala': ['Coconut ',
  'Tapioca',
  'Sugarcane',
  'Banana',
  'Rice',
  'Rubber',
  'Mango',
  'Pineapple',
  'Coffee',
  'Black pepper'],
 'Haryana': ['Sugarcane',
  'Wheat',
  'Cotton(lint)',
  'Rice',
  'Bajra',
  'Rapeseed &Mustard',
  'Potato',
  'Gram',
  'Guar seed',
  'Other Vegetables'],
 'Meghalaya': ['Potato',
  'Rice',
  'Jute',
  'Pineapple',
  'Total foodgrain',
  'Banana',
  'Dry ginger',
  'Citrus Fruit',
  'Mesta',
  'Cashewnut'],
 'West Bengal': ['Coconut ',
  'Oilseeds total',
  'Pulses total',
  'Potato',
  'Jute',
  'Rice',
  'Sugarcane',
  'Wheat',
  'Maize',
  'Rapeseed &Mustard'],
 'Arunachal Pradesh': ['Rice',
  'Oilseeds total',
  'Dry ginger',
  'Maize',
  'Sugarcane',
  'Potato',
  'Rapeseed &Mustard',
  'Small millets',
  'Wheat',
  'Dry chillies'],
 'Madhya Pradesh': ['Sugarcane',
  'Banana',
  'Wheat',
  'Soyabean',
  'Maize',
  'Rice',
  'Cotton(lint)',
  'Paddy',
  'Rapeseed &Mustard',
  'Potato'],
 'Punjab': ['Wheat',
  'Sugarcane',
  'Rice',
  'Cotton(lint)',
  'Maize',
  'Barley',
  'Groundnut',
  'Guar seed',
  'Rapeseed &Mustard',
  'Peas & beans (Pulses)'],
 'Andaman and Nicobar Islands': ['Coconut ',
  'Rice',
  'Banana',
  'Sugarcane',
  'Arecanut',
  'Tapioca',
  'Dry ginger',
  'Dry chillies',
  'Sweet potato',
  'Turmeric'],
 'Maharashtra': ['Sugarcane',
  'Banana',
  'Cotton(lint)',
  'Onion',
  'Maize',
  'Grapes',
  'Soyabean',
  'Jowar',
  'Bajra',
  'Rice'],
 'Puducherry': ['Coconut ',
  'Sugarcane',
  'Rice',
  'Paddy',
  'Tapioca',
  'Banana',
  'Mango',
  'Groundnut',
  'Urad',
  'Brinjal'],
 'Andhra Pradesh': ['Coconut ',
  'Sugarcane',
  'Rice',
  'Groundnut',
  'Cotton(lint)',
  'Maize',
  'other oilseeds',
  'Mango',
  'Mesta',
  'Banana'],
 'Uttar Pradesh': ['Sugarcane',
  'Potato',
  'Wheat',
  'Total foodgrain',
  'Rice',
  'Bajra',
  'Maize',
  'Urad',
  'Peas & beans (Pulses)',
  'Gram'],
 'Sikkim': ['Maize',
  'Total foodgrain',
  'Other Vegetables',
  'Potato',
  'Rice',
  'Small millets',
  'Other Kharif pulses',
  'Other Fresh Fruits',
  'Wheat',
  'Pulses total'],
 'Bihar': ['Sugarcane',
  'Rice',
  'Jute',
  'Wheat',
  'Maize',
  'Banana',
  'Potato',
  'Mesta',
  'Other  Rabi pulses',
  'Masoor'],
 'Telangana ': ['Coconut ',
  'Sugarcane',
  'Rice',
  'Cotton(lint)',
  'Maize',
  'Orange',
  'Soyabean',
  'Groundnut',
  'Turmeric',
  'Onion'],
 'Chhattisgarh': ['Sugarcane',
  'Rice',
  'Khesari',
  'Gram',
  'Maize',
  'Soyabean',
  'Potato',
  'Wheat',
  'Small millets',
  'Groundnut']}
