# Generated by Django 3.0.8 on 2020-07-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0004_crops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropCategory2',
        ),
    ]
