# Generated by Django 3.0.8 on 2020-07-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0005_delete_cropcategory2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crops',
        ),
    ]
