# Generated by Django 3.0.8 on 2020-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0007_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
