# Generated by Django 3.0.8 on 2020-07-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0008_crops_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crops',
        ),
    ]
