# Generated by Django 3.0.8 on 2020-07-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0009_delete_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('c_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='cropImage/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Crop_Filter', to='FarmerApp.CropFilter')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Farmer', to='FarmerApp.Farmer')),
            ],
        ),
    ]
