# Generated by Django 3.0.8 on 2020-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0010_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
