# Generated by Django 3.0.8 on 2020-07-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='crops',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
