# Generated by Django 3.0.8 on 2020-07-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0014_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropSeeds',
        ),
        migrations.DeleteModel(
            name='fertilizer',
        ),
        migrations.DeleteModel(
            name='pesticide',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
