# Generated by Django 3.0.8 on 2020-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0015_auto_20200704_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSeeds',
            fields=[
                ('p_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('s_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='cropImage/')),
                ('quality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('p_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('f_type', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='cropImage/')),
            ],
        ),
        migrations.CreateModel(
            name='pesticide',
            fields=[
                ('p_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quality', models.IntegerField()),
                ('p_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='cropImage/')),
            ],
        ),
    ]
